dep:
	npm i bootstrap jquery --save
	npm install angular-imask --save
	npm i currency-formatter --save
	npm install moment --save
	npm i toastr --save
	npm install primeng --save
	npm install primeicons --save
	npm install chart.js --save

app:
	npm i --save angular-in-memory-web-api